
const prisma =
    require("../config/database");


// ============================================================
// HELPERS
// ============================================================


// ------------------------------------------------------------
// Parse Date
// ------------------------------------------------------------

const parseDate = (
    value,
    fieldName
) => {

    const date =
        new Date(value);

    if (
        Number.isNaN(
            date.getTime()
        )
    ) {

        const error =
            new Error(
                `${fieldName} must be a valid date`
            );

        error.statusCode =
            400;

        throw error;
    }

    return date;
};


// ------------------------------------------------------------
// Round Money
// ------------------------------------------------------------

const roundMoney = (
    value
) => {

    return Number(
        Number(value).toFixed(2)
    );
};


// ------------------------------------------------------------
// Non-Negative Number
// ------------------------------------------------------------

const validateNonNegativeNumber = (
    value,
    fieldName
) => {

    const numberValue =
        Number(value);

    if (
        value === undefined ||
        value === null ||
        value === "" ||
        !Number.isFinite(
            numberValue
        ) ||
        numberValue < 0
    ) {

        const error =
            new Error(
                `${fieldName} must be greater than or equal to 0`
            );

        error.statusCode =
            400;

        throw error;
    }

    return numberValue;
};


// ------------------------------------------------------------
// Decimal To Number
// ------------------------------------------------------------

const decimalToNumber = (
    value
) => {

    if (
        value === null ||
        value === undefined
    ) {

        return 0;
    }

    return Number(value);
};


// ------------------------------------------------------------
// Start Of Day
// ------------------------------------------------------------

const startOfDay = (
    date
) => {

    const result =
        new Date(date);

    result.setHours(
        0,
        0,
        0,
        0
    );

    return result;
};


// ------------------------------------------------------------
// Service Error
// ------------------------------------------------------------

const createServiceError = (
    message,
    statusCode = 400
) => {

    const error =
        new Error(
            message
        );

    error.statusCode =
        statusCode;

    return error;
};


// ============================================================
// EMPLOYEE INCLUDE
// ============================================================

const employeeInclude = {

    branch: {

        select: {

            branchId:
                true,

            branchName:
                true,

            companyId:
                true
        }
    }
};


// ============================================================
// GET EMPLOYEE
// ============================================================

const getEmployeeById = async (
    employeeId,
    companyId
) => {

    const id =
        Number(employeeId);

    if (
        !Number.isInteger(id) ||
        id <= 0
    ) {

        throw createServiceError(
            "Invalid employeeId",
            400
        );
    }


    const employee =
        await prisma.employee.findFirst({

            where: {

                employeeId:
                    id,

                companyId:
                    Number(companyId)
            },

            include:
                employeeInclude
        });


    if (!employee) {

        throw createServiceError(
            "Employee not found",
            404
        );
    }


    return employee;
};


// ============================================================
// GET EXTRA WORK RECORDS
// ============================================================
//
// These are the ExtraWork records generated by Payroll.
//
// Payroll remains responsible for calculating:
// - regular working hours
// - shortage hours
// - extra hours
// - ExtraWork records
//
// Bonus service is responsible for managing the already
// calculated ExtraWork records.
// ============================================================

const getExtraWorkRecords = async (
    companyId,
    options = {}
) => {

    const status =
        options.status
            ? String(
                options.status
            ).toUpperCase()
            : "ACCUMULATED";


    const records =
        await prisma.extraWork.findMany({

            where: {

                status,

                employee: {

                    companyId:
                        Number(companyId)
                },

                ...(options.employeeId
                    ? {

                        employeeId:
                            Number(
                                options.employeeId
                            )
                    }
                    : {}),

                ...(options.fromDate ||
                    options.toDate
                    ? {

                        createdAt: {

                            ...(options.fromDate
                                ? {

                                    gte:
                                        parseDate(
                                            options.fromDate,
                                            "fromDate"
                                        )
                                }
                                : {}),

                            ...(options.toDate
                                ? {

                                    lte:
                                        parseDate(
                                            options.toDate,
                                            "toDate"
                                        )
                                }
                                : {})
                        }
                    }
                    : {})
            },

            include: {

                employee: {

                    include:
                        employeeInclude
                },

                payroll:
                    true,

                settlement:
                    true
            },

            orderBy: [

                {

                    createdAt:
                        "desc"
                },

                {

                    extraWorkId:
                        "desc"
                }
            ]
        });


    return records.map(
        (
            record
        ) => ({

            extraWorkId:
                record.extraWorkId,

            employeeId:
                record.employeeId,

            employee:
                record.employee,

            payrollId:
                record.payrollId,

            payPeriodStart:
                record.payroll
                    ? record.payroll.payPeriodStart
                    : null,

            payPeriodEnd:
                record.payroll
                    ? record.payroll.payPeriodEnd
                    : null,

            expectedHours:
                record.payroll
                    ? decimalToNumber(
                        record.payroll
                            .monthlyExpectedHours
                    )
                    : 0,

            regularWorkingHours:
                record.payroll
                    ? decimalToNumber(
                        record.payroll
                            .regularWorkingHours
                    )
                    : 0,

            extraHours:
                decimalToNumber(
                    record.extraHours
                ),

            status:
                record.status,

            settlementId:
                record.settlementId,

            createdAt:
                record.createdAt,

            updatedAt:
                record.updatedAt
        })
    );
};


// ============================================================
// GET BONUS / EXTRA-WORK SETTLEMENT HISTORY
// ============================================================
//
// Existing API/controller naming uses getBonusHistory().
// Keep that name so existing consumers do not needlessly break.
//
// The underlying data remains ExtraWorkSettlement.
// ============================================================

const getBonusHistory = async (
    companyId,
    options = {}
) => {

    const settlements =
        await prisma.extraWorkSettlement.findMany({

            where: {

                employee: {

                    companyId:
                        Number(companyId)
                },

                ...(options.employeeId
                    ? {

                        employeeId:
                            Number(
                                options.employeeId
                            )
                    }
                    : {})
            },

            include: {

                employee: {

                    include:
                        employeeInclude
                },

                payroll:
                    true,

                extraWorkRecords:
                    true
            },

            orderBy: [

                {

                    settlementDate:
                        "desc"
                },

                {

                    settlementId:
                        "desc"
                }
            ]
        });


    return settlements.map(
        (
            settlement
        ) => ({

            settlementId:
                settlement.settlementId,

            employeeId:
                settlement.employeeId,

            employee:
                settlement.employee,

            payrollId:
                settlement.payrollId,

            payPeriodStart:
                settlement.payroll
                    ? settlement.payroll.payPeriodStart
                    : null,

            payPeriodEnd:
                settlement.payroll
                    ? settlement.payroll.payPeriodEnd
                    : null,

            settledHours:
                decimalToNumber(
                    settlement.settledHours
                ),

            incentiveAmount:
                decimalToNumber(
                    settlement.incentiveAmount
                ),

            settlementDate:
                settlement.settlementDate,

            extraWorkRecords:
                settlement.extraWorkRecords,

            createdAt:
                settlement.createdAt,

            updatedAt:
                settlement.updatedAt
        })
    );
};


// ============================================================
// REJECT EXTRA WORK
// ============================================================
//
// Rejection does NOT delete the ExtraWork record.
//
// Historical record:
//     status = REJECTED
//
// Rejected records are excluded from future settlement because
// settlement only processes ACCUMULATED records with no
// settlementId.
// ============================================================

const rejectExtraWork = async (
    extraWorkId,
    companyId
) => {

    const id =
        Number(
            extraWorkId
        );


    if (
        !Number.isInteger(id) ||
        id <= 0
    ) {

        throw createServiceError(
            "Invalid extraWorkId",
            400
        );
    }


    const record =
        await prisma.extraWork.findFirst({

            where: {

                extraWorkId:
                    id,

                employee: {

                    companyId:
                        Number(companyId)
                }
            },

            include: {

                employee: {

                    include:
                        employeeInclude
                },

                payroll:
                    true
            }
        });


    if (!record) {

        throw createServiceError(
            "Extra-work record not found",
            404
        );
    }


    if (
        record.status ===
        "SETTLED"
    ) {

        throw createServiceError(
            "Settled extra-work records cannot be rejected",
            409
        );
    }


    if (
        record.status ===
        "REJECTED"
    ) {

        throw createServiceError(
            "Extra-work record has already been rejected",
            409
        );
    }


    const rejected =
        await prisma.extraWork.update({

            where: {

                extraWorkId:
                    id
            },

            data: {

                status:
                    "REJECTED",

                settlementId:
                    null
            },

            include: {

                employee: {

                    include:
                        employeeInclude
                },

                payroll:
                    true
            }
        });


    return {

        extraWorkId:
            rejected.extraWorkId,

        employeeId:
            rejected.employeeId,

        employee:
            rejected.employee,

        payrollId:
            rejected.payrollId,

        payPeriodStart:
            rejected.payroll
                ? rejected.payroll.payPeriodStart
                : null,

        payPeriodEnd:
            rejected.payroll
                ? rejected.payroll.payPeriodEnd
                : null,

        extraHours:
            decimalToNumber(
                rejected.extraHours
            ),

        status:
            rejected.status,

        settlementId:
            rejected.settlementId,

        createdAt:
            rejected.createdAt,

        updatedAt:
            rejected.updatedAt
    };
};


// ============================================================
// SETTLE EXTRA WORK / PAY BONUS
// ============================================================
//
// This is the payment operation moved out of Payroll.
//
// Flow:
//
// ExtraWork
//     |
//     v
// ACCUMULATED
//     |
//     v
// Admin chooses PAY
//     |
//     v
// ExtraWorkSettlement created
//     |
//     v
// ExtraWork = SETTLED
//
// IMPORTANT:
//
// This operation DOES NOT:
//
// - mark Payroll as PAID
// - modify Payroll.status
// - modify Payroll.paymentDate
// - calculate normal salary
// - recalculate extra hours
//
// incentiveAmount is the bonus amount supplied by the admin.
// ============================================================

const settleExtraWork = async (
    employeeId,
    companyId,
    incentiveAmount = 0,
    payrollId = null
) => {

    const id =
        Number(
            employeeId
        );


    if (
        !Number.isInteger(id) ||
        id <= 0
    ) {

        throw createServiceError(
            "Invalid employeeId",
            400
        );
    }


    const requestedIncentiveAmount =
        validateNonNegativeNumber(
            incentiveAmount,
            "incentiveAmount"
        );


    const employee =
        await getEmployeeById(
            id,
            companyId
        );


    let referencePayrollId =
        null;


    // --------------------------------------------------------
    // Optional Payroll Reference
    // --------------------------------------------------------

    if (
        payrollId !== null &&
        payrollId !== undefined &&
        payrollId !== ""
    ) {

        referencePayrollId =
            Number(
                payrollId
            );


        if (
            !Number.isInteger(
                referencePayrollId
            ) ||
            referencePayrollId <= 0
        ) {

            throw createServiceError(
                "Invalid payrollId",
                400
            );
        }


        const referencePayroll =
            await prisma.payroll.findFirst({

                where: {

                    payrollId:
                        referencePayrollId,

                    employeeId:
                        employee.employeeId,

                    employee: {

                        companyId:
                            Number(companyId)
                    }
                }
            });


        if (!referencePayroll) {

            throw createServiceError(
                "Reference payroll not found for this employee",
                404
            );
        }
    }


    // --------------------------------------------------------
    // ATOMIC SETTLEMENT
    // --------------------------------------------------------

    const settlement =
        await prisma.$transaction(

            async (
                transaction
            ) => {

                /*
                 * Re-read the accumulated records inside
                 * the transaction.
                 *
                 * Only ACCUMULATED records without a settlement
                 * are eligible.
                 */

                const accumulatedExtraWork =
                    await transaction.extraWork.findMany({

                        where: {

                            employeeId:
                                employee.employeeId,

                            status:
                                "ACCUMULATED",

                            settlementId:
                                null
                        },

                        orderBy: {

                            createdAt:
                                "asc"
                        }
                    });


                const settledHours =
                    roundMoney(

                        accumulatedExtraWork.reduce(

                            (
                                total,
                                record
                            ) =>

                                total +
                                decimalToNumber(
                                    record.extraHours
                                ),

                            0
                        )
                    );


                if (
                    settledHours <= 0
                ) {

                    throw createServiceError(
                        "There are no accumulated extra hours to settle",
                        400
                    );
                }


                const actualSettlementDate =
                    startOfDay(
                        new Date()
                    );


                // ------------------------------------------------
                // CREATE SETTLEMENT
                // ------------------------------------------------

                const createdSettlement =
                    await transaction
                        .extraWorkSettlement
                        .create({

                            data: {

                                employeeId:
                                    employee.employeeId,

                                /*
                                 * Historical payroll reference
                                 * only.
                                 *
                                 * This does NOT pay the payroll.
                                 */
                                payrollId:
                                    referencePayrollId,

                                settledHours,

                                incentiveAmount:
                                    requestedIncentiveAmount,

                                settlementDate:
                                    actualSettlementDate
                            }
                        });


                // ------------------------------------------------
                // MARK EXTRA WORK AS SETTLED
                // ------------------------------------------------

                await transaction.extraWork.updateMany({

                    where: {

                        extraWorkId: {

                            in:
                                accumulatedExtraWork.map(
                                    (
                                        record
                                    ) =>
                                        record.extraWorkId
                                )
                        },

                        status:
                            "ACCUMULATED",

                        settlementId:
                            null
                    },

                    data: {

                        status:
                            "SETTLED",

                        settlementId:
                            createdSettlement
                                .settlementId
                    }
                });


                return createdSettlement;
            }
        );


    // --------------------------------------------------------
    // FETCH COMPLETE SETTLEMENT
    // --------------------------------------------------------

    const result =
        await prisma.extraWorkSettlement.findUnique({

            where: {

                settlementId:
                    settlement.settlementId
            },

            include: {

                employee: {

                    include:
                        employeeInclude
                },

                payroll:
                    true,

                extraWorkRecords:
                    true
            }
        });


    if (!result) {

        throw createServiceError(
            "Bonus settlement could not be loaded after creation",
            500
        );
    }


    return {

        settlementId:
            result.settlementId,

        employeeId:
            result.employeeId,

        employee:
            result.employee,

        payrollId:
            result.payrollId,

        payPeriodStart:
            result.payroll
                ? result.payroll.payPeriodStart
                : null,

        payPeriodEnd:
            result.payroll
                ? result.payroll.payPeriodEnd
                : null,

        settledHours:
            decimalToNumber(
                result.settledHours
            ),

        incentiveAmount:
            decimalToNumber(
                result.incentiveAmount
            ),

        settlementDate:
            result.settlementDate,

        extraWorkRecords:
            result.extraWorkRecords,

        createdAt:
            result.createdAt,

        updatedAt:
            result.updatedAt
    };
};


// ============================================================
// GET EMPLOYEE BONUS / EXTRA-WORK DATA
// ============================================================
//
// Employee self-service.
//
// The employee can see:
//
// - accumulated extra hours
// - extra-work history
// - settled hours
// - bonus amounts paid
// - settlement history
//
// Employee identity must be supplied by authenticated context.
// The service verifies company ownership.
// ============================================================

const getEmployeeBonuses = async (
    employeeId,
    companyId
) => {

    const employee =
        await getEmployeeById(
            employeeId,
            companyId
        );


    // --------------------------------------------------------
    // EXTRA WORK RECORDS
    // --------------------------------------------------------

    const extraWorkRecords =
        await prisma.extraWork.findMany({

            where: {

                employeeId:
                    employee.employeeId
            },

            include: {

                payroll: {

                    select: {

                        payrollId:
                            true,

                        payPeriodStart:
                            true,

                        payPeriodEnd:
                            true,

                        monthlyExpectedHours:
                            true,

                        regularWorkingHours:
                            true
                    }
                },

                settlement:
                    true
            },

            orderBy: [

                {

                    createdAt:
                        "desc"
                },

                {

                    extraWorkId:
                        "desc"
                }
            ]
        });


    // --------------------------------------------------------
    // BONUS SETTLEMENTS
    // --------------------------------------------------------

    const settlements =
        await prisma.extraWorkSettlement.findMany({

            where: {

                employeeId:
                    employee.employeeId
            },

            include: {

                payroll: {

                    select: {

                        payrollId:
                            true,

                        payPeriodStart:
                            true,

                        payPeriodEnd:
                            true
                    }
                },

                extraWorkRecords:
                    true
            },

            orderBy: [

                {

                    settlementDate:
                        "desc"
                },

                {

                    settlementId:
                        "desc"
                }
            ]
        });


    // --------------------------------------------------------
    // FORMAT EXTRA WORK
    // --------------------------------------------------------

    const formattedExtraWork =
        extraWorkRecords.map(
            (
                record
            ) => ({

                extraWorkId:
                    record.extraWorkId,

                payrollId:
                    record.payrollId,

                payPeriodStart:
                    record.payroll
                        ? record.payroll
                            .payPeriodStart
                        : null,

                payPeriodEnd:
                    record.payroll
                        ? record.payroll
                            .payPeriodEnd
                        : null,

                expectedHours:
                    record.payroll
                        ? decimalToNumber(
                            record.payroll
                                .monthlyExpectedHours
                        )
                        : 0,

                regularWorkingHours:
                    record.payroll
                        ? decimalToNumber(
                            record.payroll
                                .regularWorkingHours
                        )
                        : 0,

                extraHours:
                    decimalToNumber(
                        record.extraHours
                    ),

                status:
                    record.status,

                settlementId:
                    record.settlementId,

                createdAt:
                    record.createdAt,

                updatedAt:
                    record.updatedAt
            })
        );


    // --------------------------------------------------------
    // FORMAT SETTLEMENTS
    // --------------------------------------------------------

    const formattedSettlements =
        settlements.map(
            (
                settlement
            ) => ({

                settlementId:
                    settlement.settlementId,

                payrollId:
                    settlement.payrollId,

                payPeriodStart:
                    settlement.payroll
                        ? settlement.payroll
                            .payPeriodStart
                        : null,

                payPeriodEnd:
                    settlement.payroll
                        ? settlement.payroll
                            .payPeriodEnd
                        : null,

                settledHours:
                    decimalToNumber(
                        settlement.settledHours
                    ),

                incentiveAmount:
                    decimalToNumber(
                        settlement.incentiveAmount
                    ),

                settlementDate:
                    settlement.settlementDate,

                extraWorkRecords:
                    settlement.extraWorkRecords,

                createdAt:
                    settlement.createdAt,

                updatedAt:
                    settlement.updatedAt
            })
        );


    // --------------------------------------------------------
    // SUMMARY
    // --------------------------------------------------------

    const totalExtraHours =
        roundMoney(

            formattedExtraWork.reduce(

                (
                    total,
                    record
                ) =>

                    total +
                    (
                        record.status ===
                        "ACCUMULATED"

                            ? record.extraHours
                            : 0
                    ),

                0
            )
        );


    const totalSettledHours =
        roundMoney(

            formattedSettlements.reduce(

                (
                    total,
                    settlement
                ) =>

                    total +
                    settlement.settledHours,

                0
            )
        );


    const totalBonusPaid =
        roundMoney(

            formattedSettlements.reduce(

                (
                    total,
                    settlement
                ) =>

                    total +
                    settlement.incentiveAmount,

                0
            )
        );


    // --------------------------------------------------------
    // RESPONSE
    // --------------------------------------------------------

    return {

        employee: {

            employeeId:
                employee.employeeId,

            firstName:
                employee.firstName,

            lastName:
                employee.lastName,

            email:
                employee.email
        },

        summary: {

            accumulatedExtraHours:
                totalExtraHours,

            totalSettledHours,

            totalBonusPaid
        },

        extraWork:
            formattedExtraWork,

        settlements:
            formattedSettlements
    };
};


// ============================================================
// EXPORTS
// ============================================================

module.exports = {

    getExtraWorkRecords,

    getBonusHistory,

    rejectExtraWork,

    settleExtraWork,

    getEmployeeBonuses

};
