const prisma = require("../../config/database");


// ============================================================
// PAYROLL CALCULATION SERVICE
// ============================================================
//
// Responsibility:
//   - Read authoritative attendance hours for a payroll period
//   - Read eligible paid public-holiday hours
//   - Calculate hourly salary rate
//   - Calculate regular payable hours
//   - Calculate shortage hours and shortage deduction
//   - Calculate extra hours generated by attendance + paid holidays
//   - Calculate the regular attendance-earned salary
//
// This service intentionally does NOT:
//   - create/update Payroll records
//   - deduct advances
//   - mark payroll as paid
//   - settle ExtraWork
//   - generate payroll for a branch
//
// Those responsibilities will live in separate payroll services.
// ============================================================


// ============================================================
// HELPER: Create Service Error
// ============================================================

const createServiceError = (
    message,
    statusCode = 400
) => {

    const error =
        new Error(message);

    error.statusCode =
        statusCode;

    return error;
};


// ============================================================
// HELPER: Parse Date
// ============================================================

const parseDate = (
    value,
    fieldName
) => {

    const date =
        value instanceof Date
            ? new Date(value.getTime())
            : new Date(value);

    if (
        Number.isNaN(
            date.getTime()
        )
    ) {

        throw createServiceError(
            `${fieldName} must be a valid date`,
            400
        );
    }

    return date;
};


// ============================================================
// HELPER: Round Money / Decimal Value
// ============================================================

const roundMoney = (
    value
) => {

    return Number(
        Number(value || 0).toFixed(2)
    );
};


// ============================================================
// HELPER: Decimal To Number
// ============================================================

const decimalToNumber = (
    value
) => {

    if (
        value === null ||
        value === undefined ||
        value === ""
    ) {

        return 0;
    }

    const numberValue =
        Number(value);

    return Number.isFinite(
        numberValue
    )
        ? numberValue
        : 0;
};


// ============================================================
// HELPER: Start Of Day
// ============================================================

const startOfDay = (
    date
) => {

    const result =
        new Date(date);

    result.setHours(
        0,
        0,
        0,
        0
    );

    return result;
};


// ============================================================
// HELPER: End Of Day
// ============================================================

const endOfDay = (
    date
) => {

    const result =
        new Date(date);

    result.setHours(
        23,
        59,
        59,
        999
    );

    return result;
};


// ============================================================
// CALCULATE HOURLY RATE
// ============================================================

const calculateHourlyRate = (
    baseSalary,
    expectedHours
) => {

    const salary =
        decimalToNumber(
            baseSalary
        );

    const hours =
        decimalToNumber(
            expectedHours
        );

    if (
        hours <= 0
    ) {

        return 0;
    }

    return roundMoney(
        salary / hours
    );
};


// ============================================================
// CALCULATE BASIC / REGULAR SALARY
// ============================================================

const calculateBasicSalary = (
    totalWorkingHours,
    salaryRatePerHour
) => {

    return roundMoney(
        decimalToNumber(
            totalWorkingHours
        ) *
        decimalToNumber(
            salaryRatePerHour
        )
    );
};


// ============================================================
// GET ATTENDANCE WORKING HOURS FOR PERIOD
// ============================================================
//
// Attendance is the authoritative source for actual fingerprint
// working hours.
//
// totalHours is preferred. When totalHours is unavailable, the
// function falls back to calculating the duration from check-in
// and check-out times.
// ============================================================

const getAttendanceWorkingHoursForPeriod = async (
    employeeId,
    payPeriodStart,
    payPeriodEnd
) => {

    const periodStart =
        parseDate(
            payPeriodStart,
            "payPeriodStart"
        );

    const periodEnd =
        parseDate(
            payPeriodEnd,
            "payPeriodEnd"
        );

    const attendanceRecords =
        await prisma.attendance.findMany({

            where: {

                employeeId:
                    Number(employeeId),

                date: {

                    gte:
                        startOfDay(
                            periodStart
                        ),

                    lte:
                        endOfDay(
                            periodEnd
                        )
                }
            },

            orderBy: {

                date:
                    "asc"
            }
        });

    let totalWorkingHours =
        0;

    for (
        const attendance
        of attendanceRecords
    ) {

        let hours =
            0;

        if (
            attendance.totalHours !== undefined &&
            attendance.totalHours !== null
        ) {

            hours =
                decimalToNumber(
                    attendance.totalHours
                );

        } else if (
            attendance.checkInTime &&
            attendance.checkOutTime
        ) {

            const attendanceDate =
                new Date(
                    attendance.date
                );

            const checkInParts =
                String(
                    attendance.checkInTime
                )
                    .slice(-8)
                    .split(":")
                    .map(Number);

            const checkOutParts =
                String(
                    attendance.checkOutTime
                )
                    .slice(-8)
                    .split(":")
                    .map(Number);

            const entry =
                new Date(
                    attendanceDate
                );

            entry.setHours(
                checkInParts[0] || 0,
                checkInParts[1] || 0,
                checkInParts[2] || 0,
                0
            );

            const exit =
                new Date(
                    attendanceDate
                );

            exit.setHours(
                checkOutParts[0] || 0,
                checkOutParts[1] || 0,
                checkOutParts[2] || 0,
                0
            );

            const difference =
                exit.getTime() -
                entry.getTime();

            if (
                difference > 0
            ) {

                hours =
                    difference /
                    (
                        1000 *
                        60 *
                        60
                    );
            }
        }

        if (
            Number.isFinite(hours) &&
            hours > 0
        ) {

            totalWorkingHours +=
                hours;
        }
    }

    return roundMoney(
        totalWorkingHours
    );
};


// ============================================================
// GET PAID PUBLIC HOLIDAY HOURS FOR PERIOD
// ============================================================

const getPaidPublicHolidayHoursForPeriod = async (
    employeeId,
    companyId,
    payPeriodStart,
    payPeriodEnd
) => {

    const employee =
        await prisma.employee.findFirst({

            where: {

                employeeId:
                    Number(employeeId),

                companyId:
                    Number(companyId)
            },

            select: {

                employeeId:
                    true,

                branchId:
                    true,

                hireDate:
                    true
            }
        });

    if (
        !employee ||
        !employee.branchId
    ) {

        return 0;
    }

    const periodStart =
        parseDate(
            payPeriodStart,
            "payPeriodStart"
        );

    const periodEnd =
        parseDate(
            payPeriodEnd,
            "payPeriodEnd"
        );

    const startDate =
        new Date(
            Date.UTC(
                periodStart.getUTCFullYear(),
                periodStart.getUTCMonth(),
                periodStart.getUTCDate()
            )
        );

    const endDate =
        new Date(
            Date.UTC(
                periodEnd.getUTCFullYear(),
                periodEnd.getUTCMonth(),
                periodEnd.getUTCDate()
            )
        );

    let effectiveStartDate =
        startDate;

    if (
        employee.hireDate
    ) {

        const hireDate =
            new Date(
                employee.hireDate
            );

        if (
            !Number.isNaN(
                hireDate.getTime()
            )
        ) {

            const hireDateUTC =
                new Date(
                    Date.UTC(
                        hireDate.getUTCFullYear(),
                        hireDate.getUTCMonth(),
                        hireDate.getUTCDate()
                    )
                );

            if (
                hireDateUTC.getTime() >
                effectiveStartDate.getTime()
            ) {

                effectiveStartDate =
                    hireDateUTC;
            }
        }
    }

    if (
        effectiveStartDate.getTime() >
        endDate.getTime()
    ) {

        return 0;
    }

    const holidays =
        await prisma.publicHoliday.findMany({

            where: {

                companyId:
                    Number(companyId),

                branchId:
                    Number(employee.branchId),

                isPaid:
                    true,

                holidayDate: {

                    gte:
                        effectiveStartDate,

                    lte:
                        endDate
                }
            },

            select: {

                dailyWorkingHours:
                    true
            }
        });

    const totalPaidHolidayHours =
        holidays.reduce(
            (
                total,
                holiday
            ) =>
                total +
                decimalToNumber(
                    holiday.dailyWorkingHours
                ),
            0
        );

    return roundMoney(
        totalPaidHolidayHours
    );
};


// ============================================================
// CALCULATE ATTENDANCE BREAKDOWN
// ============================================================

const calculateAttendanceBreakdown = (
    totalWorkingHours,
    expectedHours,
    salaryRatePerHour,
    paidHolidayHours = 0
) => {

    const actualHours =
        Math.max(
            0,
            decimalToNumber(
                totalWorkingHours
            )
        );

    const expected =
        Math.max(
            0,
            decimalToNumber(
                expectedHours
            )
        );

    const hourlyRate =
        Math.max(
            0,
            decimalToNumber(
                salaryRatePerHour
            )
        );

    const holidayHours =
        Math.max(
            0,
            decimalToNumber(
                paidHolidayHours
            )
        );

    const effectiveHours =
        actualHours +
        holidayHours;

    const regularWorkingHours =
        Math.min(
            effectiveHours,
            expected
        );

    const regularAttendanceHours =
        Math.min(
            actualHours,
            expected
        );

    const creditedHolidayHours =
        Math.max(
            0,
            regularWorkingHours -
            regularAttendanceHours
        );

    const extraHours =
        Math.max(
            effectiveHours -
            expected,
            0
        );

    const shortageHours =
        Math.max(
            expected -
            effectiveHours,
            0
        );

    const regularSalary =
        roundMoney(
            regularWorkingHours *
            hourlyRate
        );

    const shortageDeduction =
        roundMoney(
            shortageHours *
            hourlyRate
        );

    return {

        actualAttendanceHours:
            roundMoney(
                actualHours
            ),

        effectiveHours:
            roundMoney(
                effectiveHours
            ),

        expectedHours:
            roundMoney(
                expected
            ),

        salaryRatePerHour:
            roundMoney(
                hourlyRate
            ),

        regularWorkingHours:
            roundMoney(
                regularWorkingHours
            ),

        paidHolidayHours:
            roundMoney(
                holidayHours
            ),

        creditedHolidayHours:
            roundMoney(
                creditedHolidayHours
            ),

        extraHours:
            roundMoney(
                extraHours
            ),

        shortageHours:
            roundMoney(
                shortageHours
            ),

        shortageDeduction,

        regularSalary
    };
};


// ============================================================
// CALCULATE EMPLOYEE ATTENDANCE / PAYROLL BREAKDOWN
// ============================================================

const calculateEmployeeAttendanceBreakdown = async ({
    employeeId,
    companyId,
    payPeriodStart,
    payPeriodEnd,
    baseSalary,
    monthlyExpectedHours,
    salaryRatePerHour
}) => {

    if (
        employeeId === undefined ||
        employeeId === null
    ) {

        throw createServiceError(
            "employeeId is required",
            400
        );
    }

    if (
        companyId === undefined ||
        companyId === null
    ) {

        throw createServiceError(
            "companyId is required",
            400
        );
    }

    const expectedHours =
        decimalToNumber(
            monthlyExpectedHours
        );

    const resolvedHourlyRate =
        salaryRatePerHour !== undefined &&
        salaryRatePerHour !== null
            ? decimalToNumber(
                salaryRatePerHour
            )
            : calculateHourlyRate(
                baseSalary,
                expectedHours
            );

    const actualAttendanceHours =
        await getAttendanceWorkingHoursForPeriod(
            employeeId,
            payPeriodStart,
            payPeriodEnd
        );

    const paidHolidayHours =
        await getPaidPublicHolidayHoursForPeriod(
            employeeId,
            companyId,
            payPeriodStart,
            payPeriodEnd
        );

    const breakdown =
        calculateAttendanceBreakdown(
            actualAttendanceHours,
            expectedHours,
            resolvedHourlyRate,
            paidHolidayHours
        );

    return {

        employeeId:
            Number(employeeId),

        companyId:
            Number(companyId),

        payPeriodStart:
            parseDate(
                payPeriodStart,
                "payPeriodStart"
            ),

        payPeriodEnd:
            parseDate(
                payPeriodEnd,
                "payPeriodEnd"
            ),

        baseSalary:
            roundMoney(
                baseSalary
            ),

        ...breakdown
    };
};


// ============================================================
// EXPORTS
// ============================================================

module.exports = {

    roundMoney,

    decimalToNumber,

    calculateHourlyRate,

    calculateBasicSalary,

    getAttendanceWorkingHoursForPeriod,

    getPaidPublicHolidayHoursForPeriod,

    calculateAttendanceBreakdown,

    calculateEmployeeAttendanceBreakdown
};